name: landing
services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing
    networks:
      edge:
        aliases:
          - mlanding
    restart: unless-stopped

networks:
  edge:
    external: true
    name: edge 